name = "Civic"
license = "MIT"
licenselink = "https://github.com/hugo-sid/hugo-civic/blob/main/LICENSE"
description = "A Hugo theme for the U.S. Web Design System (USWDS), built for upgradeability and web performance."
homepage = "https://github.com/hugo-sid/hugo-civic"
demosite = ""
tags = ["government", "uswds", "accessibility", "section508", "performance"]
features = ["uswds", "accessible", "responsive", "multilingual", "performance-budgeted"]
min_version = "0.146.0"

[author]
  name = "Sidharth R"
  homepage = "https://github.com/hugo-sid"
